CREATE DATABASE crowdfunding_db;

USE crowdfunding_db;

CREATE TABLE CATEGORY(
CATEGORY_ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(255)
);

CREATE TABLE FUNDRAISER (
FUNDAISER_ID INT AUTO_INCREMENT PRIMARY KEY,
ORGANIZER VARCHAR(255) NOT NULL,
CAPTION TEXT,
TARGET_FUNDING DECIMAL(10,2),
CURRENT_FUNDING DECIMAL(10,2),
CITY VARCHAR(255),
ACTIVE BOOLEAN,
CATEGORY_ID INT,
FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID)
);

INSERT INTO CATEGORY (NAME) VALUES
('EDUCATION'),
('MEDICAL TREATMENT'),
('CATERING');

INSERT INTO FUNDRAISER (ORGANIZER, CAPTION, TARGET_FUNDING, CURRENT_FUNDING, CITY, ACTIVE, CATEGORY_ID) VALUES
('ALEX', 'Helping students in need', 100000.00, 50000.00, 'SYDNEY', TRUE, 1),
('BALLY', 'Relief for sick children', 500000.00, 10000.00, 'MELBOURNE', TRUE,2),
('CANDY', 'Helping low-income people with daily meals', 500000.00, 20000.00, 'BRISBANE', TRUE,3),
('DELANCY', 'Helping Dreams Education Module', 1000000.00, 500000.00, 'CAIRNS', TRUE,4),
('ELLA', 'Helping Dreams Help Homeless Module', 1000000.00, 400000.00, 'CANBERRA', TRUE,5);



